---

- name: configure the gitlab runner repository
  yum_repository:
    name: runner_gitlab-runner
    baseurl: https://packages.gitlab.com/runner/gitlab-runner/el/7/$basearch
    gpgkey: '{{ gitlab_runner_gpg_key_url }}'
    gpgcheck: yes
    enabled: no
    description: gitlab runner repository

- name: install required gitlab runner packages
  yum:
    name: '{{ gitlab_runner_package_list }}'
    enablerepo: runner_gitlab-runner
    state: present
  register: gitlab_runner_register_package_installation
  retries: 5
  delay: 2
  until: gitlab_runner_register_package_installation is success
